### ISSUE TITLE
Stability and Lifetime/Maintenance

### ISSUE THREAD

**Issue by NeverGivinUp** [snuk182/nuklear-rust#14]
Hi Serhii,

I'm planning a software project, that will cost me 1-2 years of full time to finish. I'll bet my financial existence on it. Should I use nuklear-rust for the GUI? What risks would I be taking? Do you have an estimate when it will leave beta? How long will you maintained it?

Cheers,
Navid

**Comment by snuk182** [comment]
Hi Navid,
The C library behind this project looks pretty stable. I maintain these bindings not very actively, since this is hobby project (one of). The API of it as of not is by no means stable and will be updated as long as I have some time for it. In general I'd say I do not plan to match all the C library changes immediately and update the bindings only in the major functionality or stability updates, or on demand.
Regards, Serhii.
